### PR TITLE
Fix systest bitrot.

### LINKED ISSUE #67: System tests have bitrotted.
- [ ] Mangling `os.environ` in `tests/system/requests/test_download.py` is not 2.7-compatible. (PR #77)
- [ ] `tests/system/requests/test_download.test_corrupt_download` shows a mismash on the actual hash. (Issue #76, xfailed in PR #77)
- [ ] `test_chunked_download` is getting an all-in-one response (inital response has no `Location` header, payload in body). (Issue #56, xfailed in PR #77)
- ~~Default storage class is now `MULTI_REGIONAL`, not `STANDARD`, which breaks assertions in almost all the upload tests.~~ No longer true:  the default is `STANDARD` again.
- [ ] We need to set up the CI environment to run the system tests.(PR #77)

### PR DESCRIPTION
**Pull request by tseaver**
Closes #67.

### CODE REVIEW

**Comment by tseaver** [comment]
@busunkim96, @crwilcox In order to get the system tests to run, we need to get credentials added to the `GOOGLE_APPLICATION_CREDENTIALS` environment variable on CircleCI.  I no longer have permissions for that (and don't recall how at this distance).

**Comment by busunkim96** [comment]
@tseaver I'm going to take this opportunity to move this repo to Kokoro.

**Comment by tseaver** [comment]
@busunkim96 Should I go ahead and merge this set of changes while you work on that?  AFAIK, the system tests should now run cleanly in a "stock" environment (with just the credentials file pointed to by `GOOGLE_APPLICATION_CREDENTIALS`).

**Comment by busunkim96** [comment]
@tseaver Sounds good!

**Pull request merged**
