### PR TITLE
feat: bump 'google-crc32c >= 1.0'

### PR DESCRIPTION
**Pull request by tseaver**
Uses the new namespaced-version of the library.

Release-As: 1.0.0

### CODE REVIEW

**Comment by crwilcox** [comment]
Only concern is releasing as 1.0. We have changes in the pipeline that likely will warrant a major bump

**Comment by william-silversmith** [comment]
The import bug in __init__.py that was fixed in google-crc32c 1.0.0 was impacting my users here: https://github.com/seung-lab/cloud-volume/issues/385 These problems should be fixed by default once resumable media makes a new release. Until then, I'm pinning google-crc32c to >= 1.0.0 (https://github.com/seung-lab/cloud-files/pull/20)

**Comment by tseaver** [comment]
@william-silversmith https://pypi.org/project/google-resumable-media/1.0.0/ released Tuesday.

**Comment by william-silversmith** [comment]
Thank you Tres!

**Pull request merged**
