### PR TITLE
chore(packaging): update dev status to stable

### PR DESCRIPTION
**Pull request by tseaver**
Release-As: 1.0

Fixes: #138

Blockers:

- [x] https://github.com/googleapis/python-storage/pull/212
- [x] https://github.com/googleapis/python-bigquery/pull/189
- [x] #137 / #145
- [x] Verify deployment to googleapis.dev. (See #149).

### CODE REVIEW

**Comment by tseaver** [comment]
@plamut 

> Since promoting to stable, the library version should be bumped to 1.0.0, IIRC.

The `Release-As: 1.0` tag in the commit is supposed to do that, I think.

> Possibly unrelated, but the docs linked to in the README are dated (version 0.4.1), might be worth publishing the most recent version.

I've marked this PR as blocked on #137, which involves an overall docs cleanup.

**Comment by plamut** [comment]
> The Release-As: 1.0 tag in the commit is supposed to do that, I think.

What about PyPI, doesn't it take the version label from `setup.py`?

**Comment by busunkim96** [comment]
@plamut After this PR is merged release-please will open a new PR with 1.0.0.

**Comment by tseaver** [comment]
[Systest failures](https://source.cloud.google.com/results/invocations/9c4b8536-e957-4b3e-896e-98b9850e7754/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fgoogle-resumable-media-python%2Fpresubmit%2Fpresubmit/log) in cleanup functions (unexpected 429 / 409).

**Comment by tseaver** [comment]
@plamut, @busunkim96 I believe this issue is ready for review.

**Comment by tseaver** [comment]
@busunkim96 PTAL

**Pull request merged**
