### PR TITLE
feat(resumable-media): add customizable timeouts to upload/download methods

### LINKED ISSUE #45: Add request timeout
Hi
it seems that our project, which use https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage/google/cloud/storage, is getting stuck during upload.

Although we can't confirm it with absolute certainty, it may be good idea have request timeout in resumable-media anyway.
Questions are:
- do you find a timeout good idea in general?
- should be there some well-chosen conservative implicit timeout by library (or explicit user defined timeout is preferred despite much complicated implementation because this library is only used by other google cloud platform libraries)?

We can provide eg. pull request for default timeout but we rather discuss all first.

### PR DESCRIPTION
**Pull request by plamut**
Fixes #45.

This PR adds configurable timeouts to `upload` objects.

**Motivation:**
We would like to add timeouts to BigQuery methods that depend on the file upload functionality (using resumable media), so that requests do not get stuck indefinitely at the transport layer.

Currently there is a default timeout used (61, 60), but that might not suit all use cases, hence the need for optional explicit timeout parameters.

> **CAUTION:** Changing public function signatures might break some libraries that utilize resumable media, even though the new arguments are optional, and positioned last), and this will not be caught by the test suite.
>
> It has happened recently when we added timeouts to `google-auth`, thus it is advisable that code owners of the dependent libraries have a look, too (if that is feasible).

### CODE REVIEW

**Comment by plamut** [comment]
Unit tests suite fails under Python 3.4, created an issue (https://github.com/googleapis/google-resumable-media-python/issues/117). The 3.4 tests pass, though, if ran in isolation.

**Comment by anantzoid** [comment]
I've been facing `ReadTimeout` issues while reading the data from GCS and noticed `_DEFAULT_READ_TIMEOUT = 60` cannot be changed by the user for read requests [[src](https://github.com/googleapis/google-resumable-media-python/blob/master/google/resumable_media/requests/_helpers.py#L34)].

The user should be able to specify timeout while using [`download_to_file`](https://googleapis.dev/python/storage/latest/blobs.html).

**Comment by plamut** [comment]
@busunkim96 Somehow this slipped out of the focus, and it might be a good time to revive it. Added you as a reviewer based on the GitHub's suggestion, but feel free to delegate to someone else if that makes more sense, thanks!

@anantzoid Thanks for bringing this back to attention. As this PR only adds configurable timeouts to uploads, I can add the same for the download methods, too, provided that the original [feature request](https://github.com/googleapis/google-resumable-media-python/issues/45) is confirmed (I personally don't see any reason why it shouldn't be).

**Comment by busunkim96** [comment]
LGTM'd, but adding @crwilcox since the storage folks are other primary users of this library

**Comment by plamut** [comment]
I will update the PR with timeouts to the download methods as well.

**Comment by plamut** [comment]
@crwilcox Friendly ping, can you take a look? Thanks!

**Comment by plamut** [comment]
@busunkim96 @frankyn Thanks for the reviews!

When would it be possible to release a new version of `google-resumable-media` in order to unblock https://github.com/googleapis/python-storage/pull/185 ? I hear this week is a holiday period there?

**Comment by frankyn** [comment]
Hi @plamut, let's wait until next week when everyone is back.

**Comment by plamut** [comment]
Sounds good, there's no rush.

**Pull request merged**
